/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import service.impl.HoaDonServiceImpl;
import service.impl.KhuyenMaiServiceImpl;
import viewmodel.HoaDonModel;
import viewmodel.KhuyenMaiModel;

/**
 *
 * @author hungn
 */
public class FrmKhuyenMai extends javax.swing.JFrame {

    private DefaultTableModel dtm = new DefaultTableModel();
    private DefaultTableModel dtm2 = new DefaultTableModel();
    private KhuyenMaiServiceImpl kmimpl = new KhuyenMaiServiceImpl();
    private List<KhuyenMaiModel> listkm = new ArrayList<KhuyenMaiModel>();
    private HoaDonServiceImpl hdimpl = new HoaDonServiceImpl();
    private List<HoaDonModel> listhd = new ArrayList<HoaDonModel>();

    /**
     * Creates new form FrmKhuyenMai
     */
    public FrmKhuyenMai() {
        initComponents();
        tblKhuyenMai.setModel(dtm);
        String[] header = {"Mã KM", "Tỉ Lệ KM", "Ngày BD", "Ngày KT", "Trạng Thái"};
        dtm.setColumnIdentifiers(header);
        tblHoaDon.setModel(dtm2);
        String[] header1 = {"Mã HD", "Người Tạo", "Ngày Tạo", "Tổng Tiền", "Trạng Thái"};
        dtm2.setColumnIdentifiers(header1);
        listkm = kmimpl.getAll();
        listhd = hdimpl.getHoaDonByTT("CTT");
        showData(listkm);
        showData1(listhd);
    }

    private void showData(List<KhuyenMaiModel> list) {
        dtm.setRowCount(0);
        for (KhuyenMaiModel km : list) {
            dtm.addRow(km.toDataRow());
        }
    }

    private void showData1(List<HoaDonModel> list) {
        dtm2.setRowCount(0);
        for (HoaDonModel hm : list) {
            dtm2.addRow(hm.toDataRow());
        }
    }

    private void fillData(int i) {
        KhuyenMaiModel km = listkm.get(i);
        String ngayBD = km.getNgayBatDau();
        String ngayKT = km.getNgayKetThuc();
        try {
            Date date1 = new SimpleDateFormat("dd/MM/yyyy").parse(ngayBD);
            Date date2 = new SimpleDateFormat("dd/MM/yyyy").parse(ngayKT);
            txtMaKM.setText(km.getMaKM());
            txtBatDau1.setDate(date1);
            txtKetThuc.setDate(date2);
            txtPhanTramKm.setText(String.valueOf(km.getPhanTramKM()));
            if (km.getTrangThai() == 1) {
                rdoOn.setSelected(true);
            } else {
                rdoOff.setSelected(true);
            }
        } catch (ParseException ex) {
            Logger.getLogger(FrmKhuyenMai.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private KhuyenMaiModel getKm() {
        KhuyenMaiModel km = new KhuyenMaiModel();
        try {
            km.setMaKM(txtMaKM.getText());
//            SimpleDateFormat date1 = new SimpleDateFormat("dd/MM/yyyy");
//            SimpleDateFormat date2 = new SimpleDateFormat("dd/MM/yyyy");
//            Date dat = date1.parse(km.getNgayBatDau());
//            Date dat2 = date2.parse(km.getNgayKetThuc());
            km.setNgayBatDau(String.valueOf(txtBatDau1.getDate()));
            km.setNgayKetThuc(String.valueOf(txtKetThuc.getDate()));
            float tilekm = Float.parseFloat(txtPhanTramKm.getText());
            km.setPhanTramKM(tilekm);
            km.setTrangThai(buttonGroup1.getButtonCount());
            return km;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi");
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKhuyenMai = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtKetThuc = new com.toedter.calendar.JDateChooser();
        txtBatDau1 = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMaKM = new javax.swing.JTextField();
        txtPhanTramKm = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        rdoOn = new javax.swing.JRadioButton();
        rdoOff = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblKhuyenMai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblKhuyenMai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhuyenMaiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKhuyenMai);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 770, 190));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Khuyến Mãi");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 110, 40));

        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblHoaDon);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 380, 210));

        jLabel2.setText("Ngày BD");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jLabel3.setText("Ngày KT");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, -1, -1));

        txtKetThuc.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(txtKetThuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 140, -1));

        txtBatDau1.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(txtBatDau1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 140, -1));

        jLabel4.setText("Mã KM");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        jLabel5.setText("Giá Trị");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, -1, -1));

        jLabel6.setText("Trạng Thái");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, -1, -1));
        jPanel1.add(txtMaKM, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 90, -1));
        jPanel1.add(txtPhanTramKm, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, 50, -1));

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jPanel1.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, -1, -1));

        btnCapNhat.setText("Cập Nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });
        jPanel1.add(btnCapNhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, -1, -1));

        jLabel7.setText("%");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, -1, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, -1, -1));

        buttonGroup1.add(rdoOn);
        rdoOn.setText("On");
        jPanel1.add(rdoOn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 40, -1));

        buttonGroup1.add(rdoOff);
        rdoOff.setText("Off");
        jPanel1.add(rdoOff, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 40, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblKhuyenMaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhuyenMaiMouseClicked
        int i = tblKhuyenMai.getSelectedRow();
        fillData(i);
    }//GEN-LAST:event_tblKhuyenMaiMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
//        KhuyenMaiModel km = new KhuyenMaiModel();
//        km.setMaKM(txtMaKM.getText());
//        km.setNgayBatDau(String.valueOf(txtBatDau1.getDate()));
//        km.setNgayKetThuc(String.valueOf(txtKetThuc.getDate()));
//        km.setPhanTramKM(Float.parseFloat(txtPhanTramKm.getText()));
//        int i = cbbTrangThai.getSelectedIndex();
//        km.setTrangThai(i);
//        if(new KhuyenMaiServiceImpl().Save(km)){
//            
//        } else {
//            
//        }
        KhuyenMaiModel km = new KhuyenMaiModel();
        SimpleDateFormat df = new SimpleDateFormat("dd/mm/yyyy");
        String maKm = txtMaKM.getText();
        Date ngaybd = txtBatDau1.getDate();
        Date ngaykt = txtKetThuc.getDate();
        String ngay = df.format(ngaybd);
        String ngay2 = df.format(ngaykt);
        String phanTram = txtPhanTramKm.getText();
        if (rdoOn.isSelected()) {
            km.setTrangThai(1);
        } else {
            km.setTrangThai(0);
        }
        km.setMaKM(maKm);
        km.setNgayBatDau(String.valueOf(ngay));
        km.setNgayKetThuc(String.valueOf(ngay2));
        km.setPhanTramKM(Float.parseFloat(phanTram));
        if (new KhuyenMaiServiceImpl().Save(km)) {
            JOptionPane.showMessageDialog(this, "THành công");
            listkm.add(km);
            listkm = kmimpl.getAll();
            showData(listkm);
        } else {
            JOptionPane.showMessageDialog(this, "Thất Bại");
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        KhuyenMaiModel km = new KhuyenMaiModel();
        SimpleDateFormat df = new SimpleDateFormat("dd/mm/yyyy");
        String maKm = txtMaKM.getText();
        Date ngaybd = txtBatDau1.getDate();
        Date ngaykt = txtKetThuc.getDate();
        String ngay = df.format(ngaybd);
        String ngay2 = df.format(ngaykt);
        String phanTram = txtPhanTramKm.getText();
        if (rdoOn.isSelected()) {
            km.setTrangThai(1);
        } else {
            km.setTrangThai(0);
        }
        km.setMaKM(maKm);
        km.setNgayBatDau(String.valueOf(ngay));
        km.setNgayKetThuc(String.valueOf(ngay2));
        km.setPhanTramKM(Float.parseFloat(phanTram));
        if (new KhuyenMaiServiceImpl().Update(km, maKm)) {
            JOptionPane.showMessageDialog(this, "THành công");
            listkm = kmimpl.getAll();
            showData(listkm);
        } else {
            JOptionPane.showMessageDialog(this, "THất bại");
        }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmKhuyenMai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmKhuyenMai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmKhuyenMai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmKhuyenMai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmKhuyenMai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnThem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rdoOff;
    private javax.swing.JRadioButton rdoOn;
    private javax.swing.JTable tblHoaDon;
    private javax.swing.JTable tblKhuyenMai;
    private com.toedter.calendar.JDateChooser txtBatDau1;
    private com.toedter.calendar.JDateChooser txtKetThuc;
    private javax.swing.JTextField txtMaKM;
    private javax.swing.JTextField txtPhanTramKm;
    // End of variables declaration//GEN-END:variables
}
