/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import service.impl.HoaDonServiceImpl;
import service.impl.ManageHDCTService;
import service.impl.QlyNhanVienImpl;
import viewmodel.HoaDonModel;
import viewmodel.NhanVienModel;
import viewmodel.QLHDCT;

/**
 *
 * @author hungn
 */
public class HoaDonView extends javax.swing.JFrame {

    private DefaultTableModel dtm = new DefaultTableModel();
    private DefaultTableModel dtm1 = new DefaultTableModel();
    private List<HoaDonModel> listmd1 = new ArrayList<HoaDonModel>();
    private List<QLHDCT> listsp = new ArrayList<QLHDCT>();
    private DefaultComboBoxModel dcb = new DefaultComboBoxModel();
//    private List<FormHoaDon> listmd2 = new ArrayList<>();
    private HoaDonServiceImpl hdimpl = new HoaDonServiceImpl();
    private ManageHDCTService hdct = new ManageHDCTService();
    private QlyNhanVienImpl qlnv = new QlyNhanVienImpl();
    private HoaDonModel hdm = new HoaDonModel();

    /**
     * Creates new form HoaDonView
     */
    public HoaDonView() {
        initComponents();
        tblHoaDon.setModel(dtm);
        String[] header = {"Mã HD", "Người Tạo", "Ngày Tạo", "Tổng Tiền", "Trạng Thái"};
        dtm.setColumnIdentifiers(header);
        tblSanPham.setModel(dtm1);
        String[] header1 = {"Tên SP", "Đơn Giá", "Số Lượng", "Thành Tiền"};
        dtm1.setColumnIdentifiers(header1);
        listmd1 = hdimpl.getAllHoaDon();
        cbbNhanVien.setModel(dcb);
        dcb.removeAllElements();
        for (HoaDonModel hd : listmd1) {
            dcb.addElement(hd.getHoTen());
        }
        showData(listmd1);
    }

    private void showData(List<HoaDonModel> lists) {
        dtm.setRowCount(0);
        for (HoaDonModel hd : lists) {
            dtm.addRow(hd.toDataRow());
        }
    }

    private void showDataSP(List<QLHDCT> listsp) {
        dtm1.setRowCount(0);
        for (QLHDCT sp : listsp) {
            dtm1.addRow(sp.toDataRow());
        }
    }

    private void fillData(int i) {
        HoaDonModel fhd = listmd1.get(i);
        txtMaHD.setText(String.valueOf(fhd.getIDHD()));
        txtKH.setText(fhd.getTen());
        txtSDT.setText(fhd.getSoDienThoai());
        txtTGTao.setText(fhd.getNgayTao());
        txtTGTT.setText(fhd.getNgayTT());
        txtTrangThai.setText(fhd.getTrangThai());
        txtTongTienHD.setText(String.valueOf(fhd.getTongTien()));
        txtKM.setText(String.valueOf(fhd.getPhanTramKM()));
    }

//    private void clearData() {
//        txtTenNV.setText("");
//        txtTenKH.setText("");
//        txtKM.setText("");
//        txtTienTra.setText("");
//        txtTongTien.setText("");
//        cbbTinhTrang.setSelectedIndex(0);
//        txtNgayTT.setText("");
//        txtNgayTao.setText("");
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtMaHD = new javax.swing.JLabel();
        txtKH = new javax.swing.JLabel();
        txtSDT = new javax.swing.JLabel();
        txtTGTao = new javax.swing.JLabel();
        txtTGTT = new javax.swing.JLabel();
        txtTrangThai = new javax.swing.JLabel();
        txtKM = new javax.swing.JLabel();
        txtTongTienHD = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        cbbNhanVien = new javax.swing.JComboBox<>();
        Search = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));
        jPanel1.setForeground(new java.awt.Color(204, 51, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hóa Đơn");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 6, 100, 37));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Mã HD");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 259, 51, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Khách Hàng");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 297, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("SDT");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 339, 37, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("TG Tạo");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 378, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("TG Thanh Toán");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 416, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Trạng Thái");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(716, 297, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Khuyến Mãi");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(711, 378, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Tổng Tiền HD");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(711, 416, -1, -1));

        txtMaHD.setText("X");
        jPanel1.add(txtMaHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(704, 262, 109, -1));

        txtKH.setText("X");
        jPanel1.add(txtKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 300, 133, -1));

        txtSDT.setText("X");
        jPanel1.add(txtSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 342, 107, -1));

        txtTGTao.setText("X");
        jPanel1.add(txtTGTao, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 381, 107, -1));

        txtTGTT.setText("X");
        jPanel1.add(txtTGTT, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 419, 355, -1));

        txtTrangThai.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtTrangThai.setText("X");
        jPanel1.add(txtTrangThai, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 335, 43, -1));

        txtKM.setText("X");
        jPanel1.add(txtKM, new org.netbeans.lib.awtextra.AbsoluteConstraints(811, 381, 41, -1));

        txtTongTienHD.setText("X");
        jPanel1.add(txtTongTienHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(811, 419, 113, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 102));
        jButton1.setText("Xuất File PDF");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 463, 197, 47));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("%");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(858, 378, 43, -1));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 204));
        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh Sách Hóa Đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jScrollPane2.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tblHoaDon.setBackground(new java.awt.Color(255, 255, 204));
        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDonMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblHoaDon);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 49, 948, 200));

        jScrollPane4.setBackground(new java.awt.Color(255, 255, 204));
        jScrollPane4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sản Phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jScrollPane4.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tblSanPham.setBackground(new java.awt.Color(255, 255, 204));
        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tblSanPham);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 259, 446, 235));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText("X");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(938, 0, -1, -1));

        cbbNhanVien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbbNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 30, 160, -1));

        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        jPanel1.add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 30, -1, -1));

        jButton3.setText("RS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 30, 50, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 985, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 525, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String path = "";
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int x = chooser.showSaveDialog(this);
        if (x == JFileChooser.APPROVE_OPTION) {
            path = chooser.getSelectedFile().getPath();
        }
        Document document = new Document();
        try {
            PdfWriter.getInstance(document, new FileOutputStream(path + "HoaDon.pdf"));
            document.open();
            document.add(new Paragraph("          Hoa Don Thanh Toan"));
            PdfPTable table = new PdfPTable(7);
            table.setSpacingBefore(25);
            table.setSpacingAfter(25);
            table.addCell("IDHD");
            table.addCell("Nguoi Tao");
            table.addCell("Ngay Tao");
            table.addCell("Khach Hang");
            table.addCell("San Pham");
            table.addCell("So Luong");
            table.addCell("Tong Tien");
//            int i = tblHoaDon.getSelectedRow();
//            for (int i = 0; i < tblHoaDon.getRowCount(); i++) {
//                String idhd = tblHoaDon.getValueAt(i, 0).toString();
//                String nguoiTao = tblHoaDon.getValueAt(i, 1).toString();
//                String ngayTao = tblHoaDon.getValueAt(i, 2).toString();
//                String tongTien = tblHoaDon.getValueAt(i, 3).toString();
//                String sanPham = tblSanPham.getValueAt(i, 0).toString();
//                String soLuong = tblSanPham.getValueAt(i, 2).toString();
//                String khachHang = txtKH.getText();
//                table.addCell(idhd);
//                table.addCell(nguoiTao);
//                table.addCell(ngayTao);
//                table.addCell(khachHang);
//                table.addCell(sanPham);
//                table.addCell(soLuong);
//                table.addCell(tongTien);
//            }
//                    int i = tblHoaDon.getSelectedRow();
//                    String idhd = tblHoaDon.getValueAt(i, 0).toString();
//                    String nguoiTao = tblHoaDon.getValueAt(i, 1).toString();
//                    String ngayTao = tblHoaDon.getValueAt(i, 2).toString();
//                    String tongTien = tblHoaDon.getValueAt(i, 3).toString();
//            table.addCell(idhd);
//            table.addCell(nguoiTao);
//            table.addCell(ngayTao);
//            table.addCell(tongTien);
//                    String sanPham = tblSanPham.getValueAt(i, 0).toString();
//                    String soLuong = tblSanPham.getValueAt(i, 2).toString();
//                    String data = idhd + "\n" + ngayTao + "\n ========== \n" + nguoiTao + "\n" + sanPham + "\t" + soLuong + "\n" + tongTien;
//                    table.addCell(data);
            int i = tblHoaDon.getSelectedRow();
            String idhd = tblHoaDon.getValueAt(i, 0).toString();
            String nguoiTao = tblHoaDon.getValueAt(i, 1).toString();
            String ngayTao = tblHoaDon.getValueAt(i, 2).toString();
            String tongTien = tblHoaDon.getValueAt(i, 3).toString();
            table.addCell(idhd);
            table.addCell(nguoiTao);
            table.addCell(ngayTao);
            table.addCell(tongTien);
            for(int j =0; j < tblSanPham.getRowCount(); j++){
                String sanPham = tblSanPham.getValueAt(j, 0).toString();
                String soLuong = tblSanPham.getValueAt(j, 2).toString();
                table.addCell(sanPham);
                table.addCell(soLuong);
            }
            document.add(table);
            JOptionPane.showMessageDialog(this, "In thành công");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(HoaDonView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(HoaDonView.class.getName()).log(Level.SEVERE, null, ex);
        }
        document.close();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tblHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonMouseClicked
        int i = tblHoaDon.getSelectedRow();
        fillData(i);
        HoaDonModel fhd = listmd1.get(i);
        UUID idHD = fhd.getIDHD();
        listsp = hdct.getListbyHD(idHD);
        showDataSP(listsp);
    }//GEN-LAST:event_tblHoaDonMouseClicked

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        String cbb = (String) cbbNhanVien.getSelectedItem();
        List<HoaDonModel> timTheoTen = new ArrayList<>();
        for (HoaDonModel x : hdimpl.getAllHoaDon()) {
            if (x.getHoTen().startsWith(cbb)) {
                timTheoTen.add(x);
            }
        }
        if (!timTheoTen.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Đã tìm thấy");
            showData(timTheoTen);
        } else {
            JOptionPane.showMessageDialog(this, "Không tìm thấy!");
        }
    }//GEN-LAST:event_SearchActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        showData(listmd1);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoaDonView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoaDonView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoaDonView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoaDonView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HoaDonView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Search;
    private javax.swing.JComboBox<String> cbbNhanVien;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tblHoaDon;
    private javax.swing.JTable tblSanPham;
    private javax.swing.JLabel txtKH;
    private javax.swing.JLabel txtKM;
    private javax.swing.JLabel txtMaHD;
    private javax.swing.JLabel txtSDT;
    private javax.swing.JLabel txtTGTT;
    private javax.swing.JLabel txtTGTao;
    private javax.swing.JLabel txtTongTienHD;
    private javax.swing.JLabel txtTrangThai;
    // End of variables declaration//GEN-END:variables
}
