/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import service.IManageCongThucService;
import service.IManageNguyenLieuService;
import service.impl.ManageCongThucService;
import service.impl.ManageNguyenLieuService;
import service.impl.ManageSanPhamService;
import viewmodel.QLCongThuc;
import viewmodel.QLNguyenLieu;

/**
 *
 * @author trong
 */
public class FrmQLNguyenLieu extends javax.swing.JFrame {

    IManageNguyenLieuService _iManageNguyenLieuService = new ManageNguyenLieuService();
    IManageCongThucService _iManageCongThucService = new ManageCongThucService();
    List<QLNguyenLieu> lstQLNL = _iManageNguyenLieuService.getAll();
    DefaultTableModel dtm = new DefaultTableModel();
    List<QLCongThuc> lstQLCT = _iManageCongThucService.getAll();
    DefaultComboBoxModel dcb = new DefaultComboBoxModel();
    XHelper xh = new XHelper();

    /**
     * Creates new form FrmQLCongThuc
     */
    public FrmQLNguyenLieu() {
        initComponents();
        dcb = (DefaultComboBoxModel) cboCongThuc.getModel();
        dcb.removeAllElements();
        for (QLCongThuc x : lstQLCT) {
            dcb.addElement(x.getTen());
        }
        if (cboCongThuc.getItemCount() > 0) {
            int index = cboCongThuc.getSelectedIndex();
            QLCongThuc qlct = lstQLCT.get(index);
            List<QLNguyenLieu> lstNLCT = new ManageNguyenLieuService().getByCT(qlct.getIdCT());
            loadData(lstNLCT);
        }

        // loadData(lstQLNL);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDVT = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblQLyNguyenLieu = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnSua = new javax.swing.JButton();
        txtTenNL = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        txtSL = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNgayNhap = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtHSD = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        cboCongThuc = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Số Lượng");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 186, -1, -1));

        jLabel5.setText("Đơn Vị Tính");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 220, -1, -1));
        getContentPane().add(txtDVT, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 214, 270, -1));

        tblQLyNguyenLieu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblQLyNguyenLieu.setForeground(new java.awt.Color(102, 102, 102));
        tblQLyNguyenLieu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên NL", "Số Lượng", "DVT", "Ngày Nhập", "HSD", "Tên Công Thức"
            }
        ));
        tblQLyNguyenLieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblQLyNguyenLieuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblQLyNguyenLieu);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 368, 670, 104));

        btnThem.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save.png"))); // NOI18N
        btnThem.setText("Create");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        getContentPane().add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 191, 99, -1));

        jLabel3.setText("Tên Nguyên Liệu");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 149, -1, -1));

        btnSua.setFont(new java.awt.Font("SimSun-ExtB", 1, 12)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/update.png"))); // NOI18N
        btnSua.setText("Update");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 242, -1, -1));
        getContentPane().add(txtTenNL, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 146, 270, -1));

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(51, 102, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NguyenLieuPNG.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Quản Lý Nguyên Liệu");

        btnTimKiem.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timkiem.png"))); // NOI18N
        btnTimKiem.setText("Search");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel2)
                .addGap(38, 38, 38)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTimKiem)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 6, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnTimKiem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 694, -1));
        getContentPane().add(txtSL, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 179, 270, -1));

        jLabel1.setText("Ngày Nhập");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 257, -1, -1));

        jLabel7.setText("Tên Công Thức");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 109, -1, -1));
        getContentPane().add(txtNgayNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 254, 270, -1));

        jLabel8.setText("HSD");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 297, -1, -1));
        getContentPane().add(txtHSD, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 294, 270, -1));

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backPng.png"))); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 289, 99, -1));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Close-icon_1.png"))); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, 99, -1));

        cboCongThuc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboCongThuc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboCongThucItemStateChanged(evt);
            }
        });
        cboCongThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCongThucActionPerformed(evt);
            }
        });
        getContentPane().add(cboCongThuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 106, 132, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblQLyNguyenLieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblQLyNguyenLieuMouseClicked
        int row = tblQLyNguyenLieu.getSelectedRow();
        txtTenNL.setText((String) tblQLyNguyenLieu.getValueAt(row, 1));
        txtSL.setText(tblQLyNguyenLieu.getValueAt(row, 2).toString());
        txtDVT.setText((String) tblQLyNguyenLieu.getValueAt(row, 3));
        txtNgayNhap.setText((String) tblQLyNguyenLieu.getValueAt(row, 4));
        txtHSD.setText(tblQLyNguyenLieu.getValueAt(row, 5).toString().substring(0, tblQLyNguyenLieu.getValueAt(row, 5).toString().indexOf(" ")));
        cboCongThuc.setSelectedItem(tblQLyNguyenLieu.getValueAt(row, 6));

    }//GEN-LAST:event_tblQLyNguyenLieuMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        if (xh.checkRong(txtTenNL) || xh.checkRong(txtSL) || xh.checkRong(txtNgayNhap) || xh.checkRong(txtHSD) || xh.checkRong(txtDVT)) {
            JOptionPane.showMessageDialog(this, "Điền đủ thông tin!");
            return;
        }
        try {
            if (new ManageNguyenLieuService().add(getData())) {
                JOptionPane.showMessageDialog(this, "Thêm thành công!");
                // loadData(_iManageNguyenLieuService.getAll());
                int index = cboCongThuc.getSelectedIndex();
                QLCongThuc qlct = lstQLCT.get(index);
                List<QLNguyenLieu> lstNLCT = new ManageNguyenLieuService().getByCT(qlct.getIdCT());
                loadData(lstNLCT);

            } else {
                JOptionPane.showMessageDialog(this, "Thêm thất bại!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Thêm thất bại!");
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        if (xh.checkRong(txtTenNL) || xh.checkRong(txtSL) || xh.checkRong(txtNgayNhap) || xh.checkRong(txtHSD) || xh.checkRong(txtDVT)) {
            JOptionPane.showMessageDialog(this, "Điền đủ thông tin!");
            return;
        }
        try {
            if (new ManageNguyenLieuService().getAll().size() == 0) {
                JOptionPane.showMessageDialog(this, "Hêt dữ liệu");
                return;
            }
            int index = cboCongThuc.getSelectedIndex();
            QLCongThuc qlct = lstQLCT.get(index);
            if (new ManageNguyenLieuService().update(new ManageNguyenLieuService().getByCT(qlct.getIdCT()).get(tblQLyNguyenLieu.getSelectedRow()).getIdNL(), getData())) {
                JOptionPane.showMessageDialog(this, "Sửa thành công!");

                List<QLNguyenLieu> lstNLCT = new ManageNguyenLieuService().getByCT(qlct.getIdCT());
                loadData(lstNLCT);
                // loadData(new ManageNguyenLieuService().getAll());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Sửa thất bại");
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        List<QLNguyenLieu> lstQLNLTimTheoTen = new ArrayList<>();
        for (QLNguyenLieu x : new ManageNguyenLieuService().getAll()) {
            if (x.getTenNL().toLowerCase().startsWith(txtSearch.getText().toLowerCase())) {
                lstQLNLTimTheoTen.add(x);
            }
        }
        if (lstQLNLTimTheoTen.size() != 0) {
            JOptionPane.showMessageDialog(this, "Đã tìm thấy");
            loadData(lstQLNLTimTheoTen);
        } else {
            JOptionPane.showMessageDialog(this, "Không tìm thấy!");
        }


    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        loadData(new ManageNguyenLieuService().getAll());
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void cboCongThucItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboCongThucItemStateChanged
        if (cboCongThuc.getItemCount() > 0) {
            String tenCT = cboCongThuc.getSelectedItem().toString();
            int index = cboCongThuc.getSelectedIndex();
            QLCongThuc qlct = lstQLCT.get(index);
            List<QLNguyenLieu> lstNLCT = new ManageNguyenLieuService().getByCT(qlct.getIdCT());
            loadData(lstNLCT);
        }
    }//GEN-LAST:event_cboCongThucItemStateChanged

    private void cboCongThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCongThucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboCongThucActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmQLNguyenLieu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmQLNguyenLieu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmQLNguyenLieu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmQLNguyenLieu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmQLNguyenLieu().setVisible(true);
            }
        });
//        IManageCongThucService _iManageCongThucService = new ManageCongThucService();
//        QLCongThuc qlct = _iManageCongThucService.getOneByTen("CT01");
//        System.out.println(qlct.toString());

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JComboBox<String> cboCongThuc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblQLyNguyenLieu;
    private javax.swing.JTextField txtDVT;
    private javax.swing.JTextField txtHSD;
    private javax.swing.JTextField txtNgayNhap;
    private javax.swing.JTextField txtSL;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTenNL;
    // End of variables declaration//GEN-END:variables

    private void loadData(List<QLNguyenLieu> lstqlnl) {
        dtm = (DefaultTableModel) tblQLyNguyenLieu.getModel();
        dtm.setRowCount(0);
        for (QLNguyenLieu x : lstqlnl) {
            dtm.addRow(new Object[]{lstqlnl.indexOf(x) + 1, x.getTenNL(), x.getSoLuong(), x.getDvt(), x.getNgayNhap(), x.getHsd() + " ngày", _iManageCongThucService.getOne(x.getIdCT()).getTen()});
        }
    }

    private QLNguyenLieu getData() {
        QLNguyenLieu qlnl = new QLNguyenLieu();
        try {
            qlnl.setTenNL(txtTenNL.getText());
            qlnl.setSoLuong(Integer.parseInt(txtSL.getText()));
            qlnl.setDvt(txtDVT.getText());
            qlnl.setNgayNhap(txtNgayNhap.getText());
            qlnl.setHsd(Integer.parseInt(txtHSD.getText()));
            int index = cboCongThuc.getSelectedIndex();
            qlnl.setIdCT(lstQLCT.get(index).getIdCT());
            return qlnl;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Nhập đúng trường giá trị!");
            return null;
        }
    }

    private UUID getID() {
        return new ManageNguyenLieuService().getAll().get(tblQLyNguyenLieu.getSelectedRow()).getIdNL();
    }
}
